[package]
name = "mapper-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

[[bin]]
name = "able-converter"
path = "src/main.rs"

[dependencies]
clap.workspace = true
mapper-core = { path = "../mapper-core" }
mapper-model = { path = "../mapper-model" }
serde_json.workspace = true

[lints]
workspace = true
